export { DashboardPage } from './DashboardPage'
export { SantriPage } from './SantriPage'
export { WaliPage } from './WaliPage'
export { PemasukanPage } from './PemasukanPage'
export { PengeluaranPage } from './PengeluaranPage'
export { LaporanPage } from './LaporanPage'
export { PengaturanPage } from './PengaturanPage'
